### ISSUE TITLE
Are you thinking about adding Korean?

### ISSUE THREAD

**Issue by crston** [iomatix/RPGLeveledMobs-Spigot#1]
// Korean
            MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.BAT, "박쥐");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.BLAZE, "블레이즈");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.CAVE_SPIDER, "동굴 거미");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.CHICKEN, "닭");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.COW, "소");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.CREEPER, "크리퍼");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.DONKEY, "당나귀");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ELDER_GUARDIAN, "엘더 가디언");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ENDER_DRAGON, "엔더 드래곤");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ENDERMAN, "엔더맨");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ENDERMITE, "엔더마이트");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.EVOKER, "소환사");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.GHAST, "가스트");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.GIANT, "자이언트");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.GUARDIAN, "가디언");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.HORSE, "말");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.HUSK, "허스크");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.IRON_GOLEM, "철 골렘");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.MAGMA_CUBE, "마그마 큐브");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.LLAMA, "라마");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.MULE, "노새");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.MUSHROOM_COW, "무시룸");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.OCELOT, "오실롯");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PIG, "돼지");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PIG_ZOMBIE, "좀비 피그맨");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.POLAR_BEAR, "북극곰");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.RABBIT, "토끼");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SHEEP, "양");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SHULKER, "셜커");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SILVERFISH, "좀벌레");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SKELETON, "스켈레톤");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SKELETON_HORSE, "스켈레톤 말");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SLIME, "슬라임");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SNOWMAN, "눈사람");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SPIDER, "거미");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SQUID, "오징어");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.STRAY, "스트레이");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.VEX, "벡스");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.VILLAGER, "주민");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.VINDICATOR, "변명자");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.WITCH, "마녀");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.WITHER, "위더");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.WITHER_SKELETON, "위더 스켈레톤");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.WOLF, "늑대");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ZOMBIE, "좀비");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ZOMBIE_HORSE, "좀비 말");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.ZOMBIE_VILLAGER, "좀비 주민");
			// 1.13:
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PARROT, "앵무새");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.DOLPHIN, "돌고래");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.DROWNED, "드라운드");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PHANTOM, "팬텀");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.COD, "대구");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.SALMON, "연어");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PUFFERFISH, "복어");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.TROPICAL_FISH, "열대어");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.TURTLE, "거북");
			// 1.14
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.CAT, "고양이");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.FOX, "여우");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PANDA, "판다");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.PILLAGER, "약탈자");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.RAVAGER, "파괴수");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.TRADER_LLAMA, "상인 라마");
			MobNamesMap.languageMapping.get(Language.KOREAN).put(EntityType.WANDERING_TRADER, "떠돌이 상인");

**Comment by iomatix** [comment]
Sure, thank you for the contribute!

**Comment by iomatix** [comment]
[2.4.0] - Big Languages Update
