### ISSUE TITLE
An exception

### ISSUE THREAD

**Issue by ArtelGG** [iomatix/RPGLeveledMobs-Spigot#2]
An error is being spit out into my console: [Pastebin link](https://pastebin.com/raw/UsQLhRC3).

I'm also seeing some of these, I never saw them before adding this plugin, I could be mistaken though: [Another pastebin link](https://pastebin.com/raw/ABcwCpk3).

**Comment by iomatix** [comment]
> [02:54:22 ERROR]: Can't find any space for item in the inventory

How to reproduce this error?

First one may appear if RPG leveled mobs is upgraded from version below 2.5.0 to newer.
Use **/rpgmobs clear** command to pure server from old mobs with wrong metadata values.
Try **/summon |mob|** and test is it working correctly.

**Comment by ArtelGG** [comment]
No clue, this is all on a fresh installation of the plugin, I've never upgraded before.
EDIT: The commands also need to be fixed. You can't use any of them in the console.

**Comment by ArtelGG** [comment]
Also, the commands need to be fixed. You can't use any of them in the console.

**Comment by iomatix** [comment]
The commands are usable only in game due to the architecture and the /rpgmobs settings command.
I will upload current snapshot to the official spigot's page which seems to work perfectly. (1.14.4)

**Comment by iomatix** [comment]
https://www.spigotmc.org/resources/rpg-leveled-mobs.71301/update?update=300237 
Try that one
