### ISSUE TITLE
Randomize levels

### ISSUE THREAD

**Issue by kzarius** [iomatix/RPGLeveledMobs-Spigot#3]
I would love some randomization level options, such as just a straight up randomly base level to max level allowed, and if you find it useful, a more elaborate option for biased randomness (higher levels less likely) such as outlined in [this topic](https://gamedev.stackexchange.com/questions/116832/random-number-in-a-range-biased-toward-the-low-end-of-the-range).

Thank you for your hard work. Loving the plugin, still fine-tuning the config.

**Comment by iomatix** [comment]
Sure, Just started working on it!

**Comment by iomatix** [comment]
[2.6.0]
