### ISSUE TITLE
Randomization option for MinLevel <-> MaxLevel

### ISSUE THREAD

**Issue by kzarius** [iomatix/RPGLeveledMobs-Spigot#4]
Could you add in an option to bypass the RPGLevelMax, and just use the MinLevel and MaxLevel to determine the mob level? Maybe if RPGLevelMax is 0, but RPGLevelRandomizer is still True?

Still enjoying watching my users dying from high level skeletons 👍

**Comment by iomatix** [comment]
This limiter is necessary to fix mobs migrations. It's a feature and won't be removed, just change them to 0 and 9999 if you don't need them. 
Kind Regards!

**Comment by kzarius** [comment]
I guess I'm confused about the feature, maybe you can clarify.

I want a range of say 1 (MinLevel) - 20 (MaxLevel) being the highest level possible. 1 being very common and 20 being extremely rare. I'm using the ALTER randomizer formula, but there is a variable for Maximum Rand. Level (RPGLevelMax) that skews this, and setting it to 0 seems to mean there is no randomization in levels. So, if I really want a random range of 1 - 20, where at the spawn points, something higher than level 1 cannot spawn, how would I set up the config variables?

Thanks @iomatix

**Comment by iomatix** [comment]
Set max level to 1 and mobs shouldn't spawn with higher level than 1. 
Try 1 (MinLevel) - 10 (MaxLevel) and 10 (RPGLevelMax) or 1 - 20 and 10 one of them should work. Remember  to adjust the **DistancePerLevel** Setting. 

If your desire is to globally spawn mobs randomly in range 1-20 try to set Min and Max Level to 1 and RPGLevelMax to 19. DistancePerLevel won't matter. And be sure only one Node Spawn exist. 

If an issue appears open new [bug] ticket. I will repair it as soon as possible. 

I recommend to use any character related RPG plugin with the RPG Leveled Mobs.

---------------------------

The system works like that:
1. Create The Spawn Node <- it allows to summon RPG Leveled Mobs to the World where it exist
2. Set **MinLevel** to 1 and set **MaxLevel** to desired value for the example 20 and adjust **DistancePerLevel** (!! Important !!) for example 36. Now mobs will spawn starting with 1 and increasing by 1 after 36 blocks. So 1 level mobs will spawn at the Node's location, move to next 36 blocks to reach the zone of 2 level mobs next 36 blocks 3 level etc.
3. Set **RPGLevelMax** to for example 10. Now mobs will spawn biased randomly 1-11,2-12 etc. for each step in the distance (every 36 blocks). 
**Assuming first zone where the Node is created will spawn mobs with 1-11 level range where highest value is the rarest.  36 blocks from the Node the range will change to 2-12 with this setup and goes like this 3-13, 4-14 etc.**

**Comment by kzarius** [comment]
Thank you for the clarification.

I have the settings as you've suggested on the server already, so my question is there a way to have it so that the random levels never go above the max level? My situation is that I would like the spawn areas to stay low-level, not exceeding 1-3 for instance, and the farthest away to have 1-20 levels.

**Comment by iomatix** [comment]
Create and set-up more spawn nodes. One for 1-20 and one for 1-3 in the node settings.
